# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=production
    APP_DEBUG=false
    APP_URL=http://localhost
    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=finallaravel
    DB_USERNAME=root
